### ISSUE TITLE
Host Requires Authentication 

### ISSUE THREAD

**Issue by ATStrang** [Michael-R-R/GW2_Tool_Hub#3]
Hello,

I receive an error popup when clicking 'Update Materials' that says "Error: Host requires authentication". Any idea on where to begin with troubleshooting this error?

**Comment by Michael-R-R** [comment]
Hey there,
This usually means you have not added your API key by doing the following: API>Add API Key

**Comment by ATStrang** [comment]
The API key was added without any luck on fixing the issue at hand. Any other things to try?

**Comment by Michael-R-R** [comment]
Just to make sure we are on the same page, did you install the application through downloaded .zip Installer or are you compiling, building, and running the application through Qt? 

I am assuming you installed the application through the .exe installer. If you have DB Browser installed for viewing SQLite databases you can open up the 'user.db' after adding the API key and double check to make sure that it is actually being added to the database. I will look into what else could cause that error.

**Comment by ATStrang** [comment]
> Just to make sure we are on the same page, did you install the application through downloaded .zip Installer or are you compiling, building, and running the application through Qt?
> 
> I am assuming you installed the application through the .exe installer. If you have DB Browser installed for viewing SQLite databases you can open up the 'user.db' after adding the API key and double check to make sure that it is actually being added to the database. I will look into what else could cause that error.

It was through the .exe. I will try using DB Browser to see if it's actually added in there.

**Comment by Michael-R-R** [comment]
Also the 'user.db' will be in your installation folder and the key will be under the User table

**Comment by Michael-R-R** [comment]
Also make sure you have set all permissions for when you created your api key. That is something else that could be causing the issue.
![apikey](https://user-images.githubusercontent.com/54217603/120031202-80302200-bfc6-11eb-9c6d-f0f6642c91f2.png)

**Comment by Michael-R-R** [comment]
I tested it with a strict API key with only the account tickbox checked and it gave me a 'Forbidden' error instead. The only way I can replicate the 'Host Requires Authentication' error is by completely removing my API key from the data base with the API>Remove API Key

**Comment by ATStrang** [comment]
> I tested it with a strict API key with only the account tickbox checked and it gave me a 'Forbidden' error instead. The only way I can replicate the 'Host Requires Authentication' error is by completely removing my API key from the data base with the API>Remove API Key

A quick uninstall/reinstall of Tool Hub solved the issue! Thank you for your help Michael, this is incredibly useful.

**Comment by Michael-R-R** [comment]
I am glad to hear the issue was fixed and thank you for the kind words. Take care!
